#!/bin/bash

set -e

apt update && apt install html-xml-utils -y

echo "Test starting, it will take about 5 minutes to finish. It will use docker, so make sure it was installed"

docker run --rm davidsarkany/geekbench:6.3.0 &> /tmp/geekbench.txt
cat /tmp/geekbench.txt | grep -oE "https://browser.geekbench.com/v6/cpu/[0-9]+" | head -1 > /tmp/geekbench.link.txt
curl $(cat /tmp/geekbench.link.txt) -o /tmp/geekbench.link.html

hxnormalize -l 240 -x /tmp/geekbench.link.html | hxselect -s '\n' -c "#wrap > div > div.primary.col-lg-9.order-lg-first > div.table-wrapper.cpu > div.score-container.score-container-1.desktop > div.score" > /tmp/geekbench.singlecore.txt || true

hxnormalize -l 240 -x /tmp/geekbench.link.html | hxselect -s '\n' -c "#wrap > div > div.primary.col-lg-9.order-lg-first > div.table-wrapper.cpu > div:nth-child(2) > div.score" > /tmp/geekbench.multicore.txt || true

hxnormalize -l 240 -x /tmp/geekbench.link.html | hxselect -s '\n' -c "#wrap > div > div.primary.col-lg-9.order-lg-first > div:nth-child(7) > table > tbody > tr:nth-child(2) > td.system-value" | grep -oE "[0-9]+ Cores" | grep -oE "[0-9]+" > /tmp/geekbench.cores.txt || true

hxnormalize -l 240 -x /tmp/geekbench.link.html | hxselect -s '\n' -c "#wrap > div > div.primary.col-lg-9.order-lg-first > div:nth-child(7) > table > tbody > tr:nth-child(2) > td.system-value" | grep -oE "[0-9]+ Threads" | grep -oE "[0-9]+" > /tmp/geekbench.threads.txt || true

hxnormalize -l 240 -x /tmp/geekbench.link.html | hxselect -s '\n' -c "#wrap > div > div.primary.col-lg-9.order-lg-first > div:nth-child(7) > table > tbody > tr:nth-child(1) > td.system-value > a" > /tmp/geekbench.cpuname.txt || true

echo -e "
Results:  

Cpu name:           $(cat /tmp/geekbench.cpuname.txt)
Cores count:        $(cat /tmp/geekbench.cores.txt)
Threads count:      $(cat /tmp/geekbench.threads.txt)
Single core score:  $(cat /tmp/geekbench.singlecore.txt)
Multi core score:   $(cat /tmp/geekbench.multicore.txt)
Full results link:  $(cat /tmp/geekbench.link.txt)
"

rm /tmp/geekbench*